# Generated by Django 4.1.9 on 2023-07-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_title', models.CharField(max_length=50)),
                ('answer_content', models.CharField(max_length=500)),
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.CharField(max_length=500)),
                ('question_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
